/* Generated by scripts/export_schemas.py from the Pydantic models. Do not edit. */

/**
 * Pipeline stages S0-S10 (IDEA_final §6).
 *
 * This interface was referenced by `JurisContract`'s JSON-Schema
 * via the `definition` "Stage".
 */
export type Stage = "S0" | "S1" | "S2" | "S3" | "S4" | "S5" | "S6" | "S7" | "S8" | "S9" | "S10";
/**
 * This interface was referenced by `JurisContract`'s JSON-Schema
 * via the `definition` "Event".
 */
export type Event =
  | CaseCreated
  | StageStarted
  | StageCompleted
  | AgentStarted
  | AgentCompleted
  | IssueFramed
  | QueryIssued
  | EvidenceRegistered
  | ClaimCreated
  | ClaimStatusChanged
  | ArgumentCreated
  | CounterargumentCreated
  | PrecedentCardCreated
  | VerificationResultRecorded
  | ObjectionRaised
  | ObjectionAnswered
  | UnresolvedQuestionAdded
  | JuryBallotCast
  | JuryAggregated
  | AnalysisReady
  | ValidationFailed
  | BudgetWarning
  | RunFailed
  | RunCompleted;
/**
 * Every LLM-backed role; each can get its own model.
 *
 * This interface was referenced by `JurisContract`'s JSON-Schema
 * via the `definition` "Role".
 */
export type Role =
  | "issue_framer"
  | "researcher"
  | "counsel"
  | "precedent_analyst"
  | "verifier"
  | "cross_examiner"
  | "juror"
  | "judge"
  | "baseline";
/**
 * This interface was referenced by `JurisContract`'s JSON-Schema
 * via the `definition` "DocumentKind".
 */
export type DocumentKind = "judgment" | "statute" | "other";
/**
 * This interface was referenced by `JurisContract`'s JSON-Schema
 * via the `definition` "CourtLevel".
 */
export type CourtLevel = "supreme_court" | "high_court" | "tribunal" | "subordinate";
/**
 * proposed → verified | weak | unsupported → contested → survives | falls.
 *
 * This interface was referenced by `JurisContract`'s JSON-Schema
 * via the `definition` "ClaimStatus".
 */
export type ClaimStatus = "proposed" | "verified" | "weak" | "unsupported" | "contested" | "survives" | "falls";
/**
 * This interface was referenced by `JurisContract`'s JSON-Schema
 * via the `definition` "VerificationStatus".
 */
export type VerificationStatus = "verified" | "weak" | "unsupported" | "invalid";
/**
 * The verifier's checks, cheapest first; ``check`` records the one that decided.
 *
 * This interface was referenced by `JurisContract`'s JSON-Schema
 * via the `definition` "VerificationCheck".
 */
export type VerificationCheck = "existence" | "quote" | "entailment";
/**
 * This interface was referenced by `JurisContract`'s JSON-Schema
 * via the `definition` "EntailmentLabel".
 */
export type EntailmentLabel = "supports" | "partially_supports" | "does_not_support" | "contradicts";
/**
 * How a later judgment treated a precedent (cues from PLAN 3.9).
 *
 * This interface was referenced by `JurisContract`'s JSON-Schema
 * via the `definition` "Treatment".
 */
export type Treatment = "followed" | "affirmed" | "distinguished" | "doubted" | "overruled" | "per_incuriam";
/**
 * This interface was referenced by `undefined`'s JSON-Schema definition
 * via the `patternProperty` "^A-\d{3,}$".
 *
 * This interface was referenced by `JurisContract`'s JSON-Schema
 * via the `definition` "PrecedentFit".
 */
export type PrecedentFit =
  "directly_supports" | "supports_by_analogy" | "distinguishable" | "does_not_support" | "contrary";
/**
 * This interface was referenced by `JurisContract`'s JSON-Schema
 * via the `definition` "ObjectionType".
 */
export type ObjectionType =
  | "unsupported_claim"
  | "citation_mismatch"
  | "distinguishable_precedent"
  | "overruled_or_doubted"
  | "wrong_statute_or_version"
  | "logical_gap"
  | "missing_evidence"
  | "fact_assumption";
/**
 * This interface was referenced by `JurisContract`'s JSON-Schema
 * via the `definition` "Leaning".
 */
export type Leaning = "strongly_A" | "leaning_A" | "balanced" | "leaning_B" | "strongly_B" | "insufficient_evidence";
/**
 * This interface was referenced by `JurisContract`'s JSON-Schema
 * via the `definition` "Confidence".
 */
export type Confidence = "low" | "moderate" | "high";

/**
 * Every type the backend sends to the UI (IDEA_final §12).
 */
export interface JurisContract {
  envelope: EnvelopeBase;
  event: Event;
  caseView: CaseView;
  caseAnalysis: CaseAnalysis;
}
/**
 * Fields shared by every event. Subclasses add ``type`` (a Literal) and ``payload``.
 *
 * This interface was referenced by `JurisContract`'s JSON-Schema
 * via the `definition` "EnvelopeBase".
 */
export interface EnvelopeBase {
  schema_version: string;
  event_id: string;
  run_id: string;
  case_id: string;
  /**
   * Strictly increasing per run, starting at 1
   */
  seq: number;
  ts: string;
  /**
   * None for run-level events
   */
  stage: Stage | null;
  /**
   * None for events emitted by code
   */
  agent: string | null;
}
/**
 * This interface was referenced by `JurisContract`'s JSON-Schema
 * via the `definition` "CaseCreated".
 */
export interface CaseCreated {
  schema_version: string;
  event_id: string;
  run_id: string;
  case_id: string;
  /**
   * Strictly increasing per run, starting at 1
   */
  seq: number;
  ts: string;
  /**
   * None for run-level events
   */
  stage: Stage | null;
  /**
   * None for events emitted by code
   */
  agent: string | null;
  type: "case_created";
  payload: CaseCreatedPayload;
}
/**
 * This interface was referenced by `JurisContract`'s JSON-Schema
 * via the `definition` "CaseCreatedPayload".
 */
export interface CaseCreatedPayload {
  question: string;
  profile: string;
  corpus_snapshot_id: string;
}
/**
 * This interface was referenced by `JurisContract`'s JSON-Schema
 * via the `definition` "StageStarted".
 */
export interface StageStarted {
  schema_version: string;
  event_id: string;
  run_id: string;
  case_id: string;
  /**
   * Strictly increasing per run, starting at 1
   */
  seq: number;
  ts: string;
  /**
   * None for run-level events
   */
  stage: Stage | null;
  /**
   * None for events emitted by code
   */
  agent: string | null;
  type: "stage_started";
  payload: StageStartedPayload;
}
/**
 * This interface was referenced by `JurisContract`'s JSON-Schema
 * via the `definition` "StageStartedPayload".
 */
export interface StageStartedPayload {
  mode: "on" | "passthrough";
}
/**
 * This interface was referenced by `JurisContract`'s JSON-Schema
 * via the `definition` "StageCompleted".
 */
export interface StageCompleted {
  schema_version: string;
  event_id: string;
  run_id: string;
  case_id: string;
  /**
   * Strictly increasing per run, starting at 1
   */
  seq: number;
  ts: string;
  /**
   * None for run-level events
   */
  stage: Stage | null;
  /**
   * None for events emitted by code
   */
  agent: string | null;
  type: "stage_completed";
  payload: StageCompletedPayload;
}
/**
 * This interface was referenced by `JurisContract`'s JSON-Schema
 * via the `definition` "StageCompletedPayload".
 */
export interface StageCompletedPayload {
  outcome: "completed" | "skipped" | "passthrough";
  /**
   * Why a stage was skipped
   */
  reason: string | null;
}
/**
 * This interface was referenced by `JurisContract`'s JSON-Schema
 * via the `definition` "AgentStarted".
 */
export interface AgentStarted {
  schema_version: string;
  event_id: string;
  run_id: string;
  case_id: string;
  /**
   * Strictly increasing per run, starting at 1
   */
  seq: number;
  ts: string;
  /**
   * None for run-level events
   */
  stage: Stage | null;
  /**
   * None for events emitted by code
   */
  agent: string | null;
  type: "agent_started";
  payload: AgentStartedPayload;
}
/**
 * This interface was referenced by `JurisContract`'s JSON-Schema
 * via the `definition` "AgentStartedPayload".
 */
export interface AgentStartedPayload {
  role: Role;
  model: string | null;
}
/**
 * This interface was referenced by `JurisContract`'s JSON-Schema
 * via the `definition` "AgentCompleted".
 */
export interface AgentCompleted {
  schema_version: string;
  event_id: string;
  run_id: string;
  case_id: string;
  /**
   * Strictly increasing per run, starting at 1
   */
  seq: number;
  ts: string;
  /**
   * None for run-level events
   */
  stage: Stage | null;
  /**
   * None for events emitted by code
   */
  agent: string | null;
  type: "agent_completed";
  payload: AgentCompletedPayload;
}
/**
 * This interface was referenced by `JurisContract`'s JSON-Schema
 * via the `definition` "AgentCompletedPayload".
 */
export interface AgentCompletedPayload {
  role: Role;
  input_tokens: number;
  output_tokens: number;
  cost_usd: number | null;
  cached: boolean;
}
/**
 * This interface was referenced by `JurisContract`'s JSON-Schema
 * via the `definition` "IssueFramed".
 */
export interface IssueFramed {
  schema_version: string;
  event_id: string;
  run_id: string;
  case_id: string;
  /**
   * Strictly increasing per run, starting at 1
   */
  seq: number;
  ts: string;
  /**
   * None for run-level events
   */
  stage: Stage | null;
  /**
   * None for events emitted by code
   */
  agent: string | null;
  type: "issue_framed";
  payload: IssueFramedPayload;
}
/**
 * This interface was referenced by `JurisContract`'s JSON-Schema
 * via the `definition` "IssueFramedPayload".
 */
export interface IssueFramedPayload {
  issue: Issue;
  facts: string[];
  assumptions: string[];
}
/**
 * A precise legal question with 2 (at most 3) positions.
 *
 * This interface was referenced by `JurisContract`'s JSON-Schema
 * via the `definition` "Issue".
 */
export interface Issue {
  id: string;
  question: string;
  /**
   * @minItems 2
   * @maxItems 3
   */
  positions: [Position, Position] | [Position, Position, Position];
  created_by: CreatedBy;
}
/**
 * One side of an issue, phrased neutrally.
 *
 * This interface was referenced by `JurisContract`'s JSON-Schema
 * via the `definition` "Position".
 */
export interface Position {
  id: string;
  statement: string;
}
/**
 * Which stage and agent produced an object (e.g. ``counsel_a``, ``case_record``).
 *
 * This interface was referenced by `JurisContract`'s JSON-Schema
 * via the `definition` "CreatedBy".
 */
export interface CreatedBy {
  stage: Stage;
  agent: string;
}
/**
 * This interface was referenced by `JurisContract`'s JSON-Schema
 * via the `definition` "QueryIssued".
 */
export interface QueryIssued {
  schema_version: string;
  event_id: string;
  run_id: string;
  case_id: string;
  /**
   * Strictly increasing per run, starting at 1
   */
  seq: number;
  ts: string;
  /**
   * None for run-level events
   */
  stage: Stage | null;
  /**
   * None for events emitted by code
   */
  agent: string | null;
  type: "query_issued";
  payload: QueryIssuedPayload;
}
/**
 * This interface was referenced by `JurisContract`'s JSON-Schema
 * via the `definition` "QueryIssuedPayload".
 */
export interface QueryIssuedPayload {
  query: string;
  issue_ids: string[];
}
/**
 * This interface was referenced by `JurisContract`'s JSON-Schema
 * via the `definition` "EvidenceRegistered".
 */
export interface EvidenceRegistered {
  schema_version: string;
  event_id: string;
  run_id: string;
  case_id: string;
  /**
   * Strictly increasing per run, starting at 1
   */
  seq: number;
  ts: string;
  /**
   * None for run-level events
   */
  stage: Stage | null;
  /**
   * None for events emitted by code
   */
  agent: string | null;
  type: "evidence_registered";
  payload: EvidenceRegisteredPayload;
}
/**
 * The evidence plus its document and chunk, so the UI never needs a second lookup.
 *
 * This interface was referenced by `JurisContract`'s JSON-Schema
 * via the `definition` "EvidenceRegisteredPayload".
 */
export interface EvidenceRegisteredPayload {
  evidence: Evidence;
  document: Document;
  chunk: Chunk;
}
/**
 * A retrieved chunk registered for this run. Only registered evidence may be cited.
 *
 * This interface was referenced by `JurisContract`'s JSON-Schema
 * via the `definition` "Evidence".
 */
export interface Evidence {
  id: string;
  chunk_id: string;
  document_id: string;
  /**
   * @minItems 1
   */
  issue_ids: [string, ...string[]];
  retrieval_score: number | null;
  rerank_score: number | null;
  retrieved_by_query: string;
  registered_at_stage: Stage;
  created_by: CreatedBy;
}
/**
 * A judgment or statute in a corpus snapshot.
 *
 * This interface was referenced by `JurisContract`'s JSON-Schema
 * via the `definition` "Document".
 */
export interface Document {
  id: string;
  kind: DocumentKind;
  title: string;
  court: string | null;
  court_level: CourtLevel | null;
  bench_strength: number | null;
  judges: string[];
  decision_date: string | null;
  /**
   * eCourts case number; join key (D-010)
   */
  cnr: string | null;
  /**
   * The document's own citations, e.g. '2023 INSC 1043', '[2023] 16 S.C.R. 872'
   */
  citations: string[];
  source_url: string | null;
  licence: string;
  corpus_snapshot: string;
}
/**
 * A retrievable span of a document, with paragraph (or page) provenance.
 *
 * Judgments before ~1970 have no numbered paragraphs, so they carry pages instead (D-010).
 *
 * This interface was referenced by `JurisContract`'s JSON-Schema
 * via the `definition` "Chunk".
 */
export interface Chunk {
  id: string;
  document_id: string;
  text: string;
  para_start: number | null;
  para_end: number | null;
  page_start: number | null;
  page_end: number | null;
  char_start: number;
  char_end: number;
  /**
   * Section heading, if any
   */
  section: string | null;
  statute: StatuteMeta | null;
}
/**
 * Section-level statute fields (IDEA_final §7.3, D-014).
 *
 * This interface was referenced by `JurisContract`'s JSON-Schema
 * via the `definition` "StatuteMeta".
 */
export interface StatuteMeta {
  act: string;
  section: string;
  title: string | null;
  in_force_from: string | null;
  /**
   * None = still in force
   */
  in_force_to: string | null;
  amended_by: string[];
  /**
   * True only if dates came from configs/statutes/amendments.yaml
   */
  amendments_curated: boolean;
}
/**
 * This interface was referenced by `JurisContract`'s JSON-Schema
 * via the `definition` "ClaimCreated".
 */
export interface ClaimCreated {
  schema_version: string;
  event_id: string;
  run_id: string;
  case_id: string;
  /**
   * Strictly increasing per run, starting at 1
   */
  seq: number;
  ts: string;
  /**
   * None for run-level events
   */
  stage: Stage | null;
  /**
   * None for events emitted by code
   */
  agent: string | null;
  type: "claim_created";
  payload: ClaimCreatedPayload;
}
/**
 * This interface was referenced by `JurisContract`'s JSON-Schema
 * via the `definition` "ClaimCreatedPayload".
 */
export interface ClaimCreatedPayload {
  claim: Claim;
}
/**
 * An atomic legal proposition put forward for a position.
 *
 * This interface was referenced by `JurisContract`'s JSON-Schema
 * via the `definition` "Claim".
 */
export interface Claim {
  id: string;
  text: string;
  position_id: string;
  author_agent: string;
  status: ClaimStatus;
  created_by: CreatedBy;
}
/**
 * This interface was referenced by `JurisContract`'s JSON-Schema
 * via the `definition` "ClaimStatusChanged".
 */
export interface ClaimStatusChanged {
  schema_version: string;
  event_id: string;
  run_id: string;
  case_id: string;
  /**
   * Strictly increasing per run, starting at 1
   */
  seq: number;
  ts: string;
  /**
   * None for run-level events
   */
  stage: Stage | null;
  /**
   * None for events emitted by code
   */
  agent: string | null;
  type: "claim_status_changed";
  payload: ClaimStatusChangedPayload;
}
/**
 * This interface was referenced by `JurisContract`'s JSON-Schema
 * via the `definition` "ClaimStatusChangedPayload".
 */
export interface ClaimStatusChangedPayload {
  claim_id: string;
  status: ClaimStatus;
  reason: string;
}
/**
 * This interface was referenced by `JurisContract`'s JSON-Schema
 * via the `definition` "ArgumentCreated".
 */
export interface ArgumentCreated {
  schema_version: string;
  event_id: string;
  run_id: string;
  case_id: string;
  /**
   * Strictly increasing per run, starting at 1
   */
  seq: number;
  ts: string;
  /**
   * None for run-level events
   */
  stage: Stage | null;
  /**
   * None for events emitted by code
   */
  agent: string | null;
  type: "argument_created";
  payload: ArgumentCreatedPayload;
}
/**
 * This interface was referenced by `JurisContract`'s JSON-Schema
 * via the `definition` "ArgumentCreatedPayload".
 */
export interface ArgumentCreatedPayload {
  argument: Argument;
}
/**
 * Links claims to evidence with short, structured reasoning.
 *
 * This interface was referenced by `JurisContract`'s JSON-Schema
 * via the `definition` "Argument".
 */
export interface Argument {
  id: string;
  /**
   * @minItems 1
   */
  claim_ids: [string, ...string[]];
  reasoning: string;
  citations: Citation[];
  created_by: CreatedBy;
}
/**
 * A claim's link to evidence: pinpoint plus a verbatim quote from the chunk.
 *
 * This interface was referenced by `JurisContract`'s JSON-Schema
 * via the `definition` "Citation".
 */
export interface Citation {
  claim_id: string;
  evidence_id: string;
  /**
   * Paragraph or page, e.g. 'para 12' or 'p. 358'
   */
  pinpoint: string;
  /**
   * Must be an exact normalised substring of the chunk
   */
  quote: string;
  verification: VerificationResult | null;
}
/**
 * The Citation Verifier's verdict on one citation (S4/S7/S10).
 *
 * This interface was referenced by `JurisContract`'s JSON-Schema
 * via the `definition` "VerificationResult".
 */
export interface VerificationResult {
  status: VerificationStatus;
  check: VerificationCheck;
  /**
   * Set by the entailment check
   */
  label: EntailmentLabel | null;
  justification: string;
  /**
   * None for code-only checks
   */
  verifier_model: string | null;
  created_by: CreatedBy;
}
/**
 * This interface was referenced by `JurisContract`'s JSON-Schema
 * via the `definition` "CounterargumentCreated".
 */
export interface CounterargumentCreated {
  schema_version: string;
  event_id: string;
  run_id: string;
  case_id: string;
  /**
   * Strictly increasing per run, starting at 1
   */
  seq: number;
  ts: string;
  /**
   * None for run-level events
   */
  stage: Stage | null;
  /**
   * None for events emitted by code
   */
  agent: string | null;
  type: "counterargument_created";
  payload: CounterargumentCreatedPayload;
}
/**
 * This interface was referenced by `JurisContract`'s JSON-Schema
 * via the `definition` "CounterargumentCreatedPayload".
 */
export interface CounterargumentCreatedPayload {
  counterargument: Counterargument;
}
/**
 * A rebuttal (S5) aimed at a specific opposing claim.
 *
 * This interface was referenced by `JurisContract`'s JSON-Schema
 * via the `definition` "Counterargument".
 */
export interface Counterargument {
  id: string;
  targets: string;
  argument_id: string;
  created_by: CreatedBy;
}
/**
 * This interface was referenced by `JurisContract`'s JSON-Schema
 * via the `definition` "PrecedentCardCreated".
 */
export interface PrecedentCardCreated {
  schema_version: string;
  event_id: string;
  run_id: string;
  case_id: string;
  /**
   * Strictly increasing per run, starting at 1
   */
  seq: number;
  ts: string;
  /**
   * None for run-level events
   */
  stage: Stage | null;
  /**
   * None for events emitted by code
   */
  agent: string | null;
  type: "precedent_card_created";
  payload: PrecedentCardCreatedPayload;
}
/**
 * This interface was referenced by `JurisContract`'s JSON-Schema
 * via the `definition` "PrecedentCardCreatedPayload".
 */
export interface PrecedentCardCreatedPayload {
  card: PrecedentCard;
}
/**
 * The Precedent Analyst's assessment of one cited judgment (S3).
 *
 * Unknown treatment is ``treatment=[]`` with ``treatment_verified=False``: never good law
 * by default (IDEA_final §9, D-013).
 *
 * This interface was referenced by `JurisContract`'s JSON-Schema
 * via the `definition` "PrecedentCard".
 */
export interface PrecedentCard {
  document_id: string;
  /**
   * The ratio as the model reads it
   */
  principle: string;
  principle_source: "model_extracted";
  material_facts: string;
  distinguishing_factors: string[];
  treatment: TreatmentSignal[];
  treatment_verified: boolean;
  fit_by_argument: {
    [k: string]: PrecedentFit;
  };
  created_by: CreatedBy;
}
/**
 * A treatment cue in the corpus: a later judgment that followed, overruled, ... this one.
 *
 * This interface was referenced by `JurisContract`'s JSON-Schema
 * via the `definition` "TreatmentSignal".
 */
export interface TreatmentSignal {
  kind: Treatment;
  by_document_id: string;
  cue_text: string;
}
/**
 * This interface was referenced by `JurisContract`'s JSON-Schema
 * via the `definition` "VerificationResultRecorded".
 */
export interface VerificationResultRecorded {
  schema_version: string;
  event_id: string;
  run_id: string;
  case_id: string;
  /**
   * Strictly increasing per run, starting at 1
   */
  seq: number;
  ts: string;
  /**
   * None for run-level events
   */
  stage: Stage | null;
  /**
   * None for events emitted by code
   */
  agent: string | null;
  type: "verification_result";
  payload: VerificationResultPayload;
}
/**
 * This interface was referenced by `JurisContract`'s JSON-Schema
 * via the `definition` "VerificationResultPayload".
 */
export interface VerificationResultPayload {
  claim_id: string;
  evidence_id: string;
  result: VerificationResult;
}
/**
 * This interface was referenced by `JurisContract`'s JSON-Schema
 * via the `definition` "ObjectionRaised".
 */
export interface ObjectionRaised {
  schema_version: string;
  event_id: string;
  run_id: string;
  case_id: string;
  /**
   * Strictly increasing per run, starting at 1
   */
  seq: number;
  ts: string;
  /**
   * None for run-level events
   */
  stage: Stage | null;
  /**
   * None for events emitted by code
   */
  agent: string | null;
  type: "objection_raised";
  payload: ObjectionRaisedPayload;
}
/**
 * This interface was referenced by `JurisContract`'s JSON-Schema
 * via the `definition` "ObjectionRaisedPayload".
 */
export interface ObjectionRaisedPayload {
  objection: Objection;
}
/**
 * A Cross-Examiner objection (S6) against a claim, citation, argument, ... ID.
 *
 * This interface was referenced by `JurisContract`'s JSON-Schema
 * via the `definition` "Objection".
 */
export interface Objection {
  id: string;
  type: ObjectionType;
  target_id: string;
  raised_by: string;
  text: string;
  /**
   * The targeted counsel's one reply
   */
  response: string | null;
  resolved: boolean;
  created_by: CreatedBy;
}
/**
 * This interface was referenced by `JurisContract`'s JSON-Schema
 * via the `definition` "ObjectionAnswered".
 */
export interface ObjectionAnswered {
  schema_version: string;
  event_id: string;
  run_id: string;
  case_id: string;
  /**
   * Strictly increasing per run, starting at 1
   */
  seq: number;
  ts: string;
  /**
   * None for run-level events
   */
  stage: Stage | null;
  /**
   * None for events emitted by code
   */
  agent: string | null;
  type: "objection_answered";
  payload: ObjectionAnsweredPayload;
}
/**
 * This interface was referenced by `JurisContract`'s JSON-Schema
 * via the `definition` "ObjectionAnsweredPayload".
 */
export interface ObjectionAnsweredPayload {
  objection_id: string;
  response: string;
  resolved: boolean;
}
/**
 * This interface was referenced by `JurisContract`'s JSON-Schema
 * via the `definition` "UnresolvedQuestionAdded".
 */
export interface UnresolvedQuestionAdded {
  schema_version: string;
  event_id: string;
  run_id: string;
  case_id: string;
  /**
   * Strictly increasing per run, starting at 1
   */
  seq: number;
  ts: string;
  /**
   * None for run-level events
   */
  stage: Stage | null;
  /**
   * None for events emitted by code
   */
  agent: string | null;
  type: "unresolved_question_added";
  payload: UnresolvedQuestionAddedPayload;
}
/**
 * This interface was referenced by `JurisContract`'s JSON-Schema
 * via the `definition` "UnresolvedQuestionAddedPayload".
 */
export interface UnresolvedQuestionAddedPayload {
  question: string;
  issue_id: string | null;
  from_objection_id: string | null;
}
/**
 * This interface was referenced by `JurisContract`'s JSON-Schema
 * via the `definition` "JuryBallotCast".
 */
export interface JuryBallotCast {
  schema_version: string;
  event_id: string;
  run_id: string;
  case_id: string;
  /**
   * Strictly increasing per run, starting at 1
   */
  seq: number;
  ts: string;
  /**
   * None for run-level events
   */
  stage: Stage | null;
  /**
   * None for events emitted by code
   */
  agent: string | null;
  type: "jury_ballot_cast";
  payload: JuryBallotCastPayload;
}
/**
 * This interface was referenced by `JurisContract`'s JSON-Schema
 * via the `definition` "JuryBallotCastPayload".
 */
export interface JuryBallotCastPayload {
  ballot: JuryBallot;
}
/**
 * One juror's independent scores (S8). Jurors cannot add evidence.
 *
 * This interface was referenced by `JurisContract`'s JSON-Schema
 * via the `definition` "JuryBallot".
 */
export interface JuryBallot {
  juror_id: string;
  per_position_scores: {
    [k: string]: RubricScores;
  };
  /**
   * @minItems 1
   */
  justifications: [Justification, ...Justification[]];
  created_by: CreatedBy;
}
/**
 * The jury rubric for one position (IDEA_final §6.1), each scored 1-5.
 *
 * This interface was referenced by `undefined`'s JSON-Schema definition
 * via the `patternProperty` "^I-\d+\.[A-C]$".
 *
 * This interface was referenced by `JurisContract`'s JSON-Schema
 * via the `definition` "RubricScores".
 */
export interface RubricScores {
  evidence_strength: number;
  precedent_fit: number;
  counterargument_handling: number;
  unresolved_risk: number;
}
/**
 * This interface was referenced by `JurisContract`'s JSON-Schema
 * via the `definition` "Justification".
 */
export interface Justification {
  text: string;
  /**
   * Evidence/claim/objection IDs
   *
   * @minItems 1
   */
  cited_ids: [string, ...string[]];
}
/**
 * This interface was referenced by `JurisContract`'s JSON-Schema
 * via the `definition` "JuryAggregated".
 */
export interface JuryAggregated {
  schema_version: string;
  event_id: string;
  run_id: string;
  case_id: string;
  /**
   * Strictly increasing per run, starting at 1
   */
  seq: number;
  ts: string;
  /**
   * None for run-level events
   */
  stage: Stage | null;
  /**
   * None for events emitted by code
   */
  agent: string | null;
  type: "jury_aggregated";
  payload: JuryAggregatedPayload;
}
/**
 * Deterministic aggregate of all ballots: per position, per rubric criterion.
 *
 * This interface was referenced by `JurisContract`'s JSON-Schema
 * via the `definition` "JuryAggregatedPayload".
 */
export interface JuryAggregatedPayload {
  per_position: {
    /**
     * This interface was referenced by `undefined`'s JSON-Schema definition
     * via the `patternProperty` "^I-\d+\.[A-C]$".
     */
    [k: string]: {
      [k: string]: ScoreStats;
    };
  };
  /**
   * High spread: flagged for the Judge
   */
  contested_issue_ids: string[];
}
/**
 * This interface was referenced by `JurisContract`'s JSON-Schema
 * via the `definition` "ScoreStats".
 */
export interface ScoreStats {
  mean: number;
  /**
   * Max minus min across jurors
   */
  spread: number;
}
/**
 * This interface was referenced by `JurisContract`'s JSON-Schema
 * via the `definition` "AnalysisReady".
 */
export interface AnalysisReady {
  schema_version: string;
  event_id: string;
  run_id: string;
  case_id: string;
  /**
   * Strictly increasing per run, starting at 1
   */
  seq: number;
  ts: string;
  /**
   * None for run-level events
   */
  stage: Stage | null;
  /**
   * None for events emitted by code
   */
  agent: string | null;
  type: "analysis_ready";
  payload: AnalysisReadyPayload;
}
/**
 * This interface was referenced by `JurisContract`'s JSON-Schema
 * via the `definition` "AnalysisReadyPayload".
 */
export interface AnalysisReadyPayload {
  analysis: CaseAnalysis;
}
/**
 * The Judge's final analysis. Gives a leaning per issue, never a verdict.
 *
 * Checks that need the whole Case Record (citations only to verified/weak evidence,
 * every S0 issue covered, unverified treatment listed in ``limitations``) are enforced
 * by the Case Record, not here.
 *
 * This interface was referenced by `JurisContract`'s JSON-Schema
 * via the `definition` "CaseAnalysis".
 */
export interface CaseAnalysis {
  question: string;
  facts: string[];
  assumptions: string[];
  /**
   * @minItems 1
   */
  issues: [IssueAnalysis, ...IssueAnalysis[]];
  overall_summary: string;
  limitations: string[];
  sources: SourceRef[];
  disclaimer: string;
  created_by: CreatedBy;
}
/**
 * This interface was referenced by `JurisContract`'s JSON-Schema
 * via the `definition` "IssueAnalysis".
 */
export interface IssueAnalysis {
  issue_id: string;
  issue_text: string;
  /**
   * @minItems 2
   * @maxItems 3
   */
  positions: [PositionAnalysis, PositionAnalysis] | [PositionAnalysis, PositionAnalysis, PositionAnalysis];
  key_conflicts: KeyConflict[];
  leaning: Leaning;
  confidence: Confidence;
  confidence_reason: string;
  unresolved_questions: string[];
}
/**
 * This interface was referenced by `JurisContract`'s JSON-Schema
 * via the `definition` "PositionAnalysis".
 */
export interface PositionAnalysis {
  position_id: string;
  summary: string;
  supporting_authorities: string[];
  key_evidence: EvidenceRef[];
}
/**
 * This interface was referenced by `JurisContract`'s JSON-Schema
 * via the `definition` "EvidenceRef".
 */
export interface EvidenceRef {
  evidence_id: string;
  pinpoint: string;
}
/**
 * Two authorities that pull in different directions, and which weighs more.
 *
 * This interface was referenced by `JurisContract`'s JSON-Schema
 * via the `definition` "KeyConflict".
 */
export interface KeyConflict {
  authority_a: string;
  authority_b: string;
  distinction: string;
  /**
   * None if neither prevails
   */
  weightier: string | null;
  reason: string;
}
/**
 * This interface was referenced by `JurisContract`'s JSON-Schema
 * via the `definition` "SourceRef".
 */
export interface SourceRef {
  document_id: string;
  court: string | null;
  date: string | null;
  citation: string | null;
  pinpoints_used: string[];
  link: string | null;
}
/**
 * This interface was referenced by `JurisContract`'s JSON-Schema
 * via the `definition` "ValidationFailed".
 */
export interface ValidationFailed {
  schema_version: string;
  event_id: string;
  run_id: string;
  case_id: string;
  /**
   * Strictly increasing per run, starting at 1
   */
  seq: number;
  ts: string;
  /**
   * None for run-level events
   */
  stage: Stage | null;
  /**
   * None for events emitted by code
   */
  agent: string | null;
  type: "validation_failed";
  payload: ValidationFailedPayload;
}
/**
 * This interface was referenced by `JurisContract`'s JSON-Schema
 * via the `definition` "ValidationFailedPayload".
 */
export interface ValidationFailedPayload {
  /**
   * @minItems 1
   */
  errors: [string, ...string[]];
  /**
   * What was dropped after the repair
   */
  dropped: string | null;
}
/**
 * This interface was referenced by `JurisContract`'s JSON-Schema
 * via the `definition` "BudgetWarning".
 */
export interface BudgetWarning {
  schema_version: string;
  event_id: string;
  run_id: string;
  case_id: string;
  /**
   * Strictly increasing per run, starting at 1
   */
  seq: number;
  ts: string;
  /**
   * None for run-level events
   */
  stage: Stage | null;
  /**
   * None for events emitted by code
   */
  agent: string | null;
  type: "budget_warning";
  payload: BudgetWarningPayload;
}
/**
 * This interface was referenced by `JurisContract`'s JSON-Schema
 * via the `definition` "BudgetWarningPayload".
 */
export interface BudgetWarningPayload {
  tokens_used: number;
  tokens_budget: number | null;
  usd_used: number;
  usd_budget: number | null;
  /**
   * What the orchestrator skipped or reduced
   */
  action: string;
}
/**
 * This interface was referenced by `JurisContract`'s JSON-Schema
 * via the `definition` "RunFailed".
 */
export interface RunFailed {
  schema_version: string;
  event_id: string;
  run_id: string;
  case_id: string;
  /**
   * Strictly increasing per run, starting at 1
   */
  seq: number;
  ts: string;
  /**
   * None for run-level events
   */
  stage: Stage | null;
  /**
   * None for events emitted by code
   */
  agent: string | null;
  type: "run_failed";
  payload: RunFailedPayload;
}
/**
 * This interface was referenced by `JurisContract`'s JSON-Schema
 * via the `definition` "RunFailedPayload".
 */
export interface RunFailedPayload {
  reason: string;
}
/**
 * This interface was referenced by `JurisContract`'s JSON-Schema
 * via the `definition` "RunCompleted".
 */
export interface RunCompleted {
  schema_version: string;
  event_id: string;
  run_id: string;
  case_id: string;
  /**
   * Strictly increasing per run, starting at 1
   */
  seq: number;
  ts: string;
  /**
   * None for run-level events
   */
  stage: Stage | null;
  /**
   * None for events emitted by code
   */
  agent: string | null;
  type: "run_completed";
  payload: RunCompletedPayload;
}
/**
 * This interface was referenced by `JurisContract`'s JSON-Schema
 * via the `definition` "RunCompletedPayload".
 */
export interface RunCompletedPayload {
  totals: RunTotals;
}
/**
 * This interface was referenced by `JurisContract`'s JSON-Schema
 * via the `definition` "RunTotals".
 */
export interface RunTotals {
  llm_calls: number;
  cached_calls: number;
  input_tokens: number;
  output_tokens: number;
  usd: number;
  unpriced_calls: number;
}
/**
 * Everything the UI shows for one run. Dicts keep insertion (= event) order.
 *
 * This interface was referenced by `JurisContract`'s JSON-Schema
 * via the `definition` "CaseView".
 */
export interface CaseView {
  run_id: string;
  case_id: string;
  question: string;
  profile: string;
  corpus_snapshot_id: string;
  status: "running" | "completed" | "failed";
  error: string | null;
  current_stage: Stage | null;
  stages: {
    [k: string]: StageState;
  };
  agents: {
    [k: string]: AgentState;
  };
  facts: string[];
  assumptions: string[];
  issues: {
    [k: string]: Issue;
  };
  queries: QueryRecord[];
  documents: {
    [k: string]: Document;
  };
  chunks: {
    [k: string]: Chunk;
  };
  evidence: {
    [k: string]: Evidence;
  };
  claims: {
    [k: string]: Claim;
  };
  arguments: {
    [k: string]: Argument;
  };
  counterarguments: {
    [k: string]: Counterargument;
  };
  precedent_cards: {
    [k: string]: PrecedentCard;
  };
  objections: {
    [k: string]: Objection;
  };
  unresolved_questions: UnresolvedQuestion[];
  verifications: VerificationRecord[];
  jury_ballots: {
    [k: string]: JuryBallot;
  };
  jury_aggregate: JuryAggregatedPayload | null;
  validation_failures: ValidationFailure[];
  budget_warnings: BudgetWarningPayload[];
  analysis: CaseAnalysis | null;
  totals: RunTotals | null;
  timeline: TimelineEntry[];
}
/**
 * This interface was referenced by `JurisContract`'s JSON-Schema
 * via the `definition` "StageState".
 */
export interface StageState {
  status: "running" | "completed" | "skipped" | "passthrough";
  reason: string | null;
}
/**
 * This interface was referenced by `JurisContract`'s JSON-Schema
 * via the `definition` "AgentState".
 */
export interface AgentState {
  role: Role;
  status: "running" | "done";
  model: string | null;
  input_tokens: number;
  output_tokens: number;
  cost_usd: number | null;
}
/**
 * This interface was referenced by `JurisContract`'s JSON-Schema
 * via the `definition` "QueryRecord".
 */
export interface QueryRecord {
  query: string;
  issue_ids: string[];
  stage: Stage | null;
  agent: string | null;
}
/**
 * This interface was referenced by `JurisContract`'s JSON-Schema
 * via the `definition` "UnresolvedQuestion".
 */
export interface UnresolvedQuestion {
  question: string;
  issue_id: string | null;
  from_objection_id: string | null;
}
/**
 * This interface was referenced by `JurisContract`'s JSON-Schema
 * via the `definition` "VerificationRecord".
 */
export interface VerificationRecord {
  claim_id: string;
  evidence_id: string;
  result: VerificationResult;
  seq: number;
}
/**
 * This interface was referenced by `JurisContract`'s JSON-Schema
 * via the `definition` "ValidationFailure".
 */
export interface ValidationFailure {
  stage: Stage | null;
  agent: string | null;
  errors: string[];
  dropped: string | null;
}
/**
 * This interface was referenced by `JurisContract`'s JSON-Schema
 * via the `definition` "TimelineEntry".
 */
export interface TimelineEntry {
  seq: number;
  event_id: string;
  ts: string;
  type: string;
  stage: Stage | null;
  agent: string | null;
}
