"""The final output: ``CaseAnalysis`` (IDEA_final §10)."""

import datetime as dt
from typing import Annotated, Self

from pydantic import Field, StringConstraints, model_validator

from juris.models.common import (
    Confidence,
    CreatedBy,
    DocumentId,
    EvidenceId,
    IssueId,
    JurisModel,
    Leaning,
    PositionId,
)

Text = Annotated[str, StringConstraints(min_length=1)]

DISCLAIMER = (
    "This is a research output generated by an automated system. It is not legal advice "
    "and not a judgment. Verify every authority against the official source before relying on it."
)
SUMMARY_MAX_WORDS = 250


class EvidenceRef(JurisModel):
    evidence_id: EvidenceId
    pinpoint: Text


class PositionAnalysis(JurisModel):
    position_id: PositionId
    summary: Text
    supporting_authorities: list[DocumentId] = Field(default_factory=list)
    key_evidence: list[EvidenceRef] = Field(default_factory=list)


class KeyConflict(JurisModel):
    """Two authorities that pull in different directions, and which weighs more."""

    authority_a: DocumentId
    authority_b: DocumentId
    distinction: Text
    weightier: DocumentId | None = Field(default=None, description="None if neither prevails")
    reason: Text

    @model_validator(mode="after")
    def _weightier_is_one_of_them(self) -> Self:
        if self.weightier not in (None, self.authority_a, self.authority_b):
            raise ValueError("weightier must be authority_a, authority_b or None")
        return self


class IssueAnalysis(JurisModel):
    issue_id: IssueId
    issue_text: Text
    positions: list[PositionAnalysis] = Field(min_length=2, max_length=3)
    key_conflicts: list[KeyConflict] = Field(default_factory=list)
    leaning: Leaning
    confidence: Confidence
    confidence_reason: Text
    unresolved_questions: list[str] = Field(default_factory=list)

    @model_validator(mode="after")
    def _positions_belong(self) -> Self:
        if any(not p.position_id.startswith(f"{self.issue_id}.") for p in self.positions):
            raise ValueError(f"every position must belong to {self.issue_id}")
        return self


class SourceRef(JurisModel):
    document_id: DocumentId
    court: str | None = None
    date: dt.date | None = None
    citation: str | None = None
    pinpoints_used: list[str] = Field(default_factory=list)
    link: str | None = None


class CaseAnalysis(JurisModel):
    """The Judge's final analysis. Gives a leaning per issue, never a verdict.

    Checks that need the whole Case Record (citations only to verified/weak evidence,
    every S0 issue covered, unverified treatment listed in ``limitations``) are enforced
    by the Case Record, not here.
    """

    question: Text
    facts: list[str] = Field(default_factory=list)
    assumptions: list[str] = Field(default_factory=list)
    issues: list[IssueAnalysis] = Field(min_length=1)
    overall_summary: Text
    limitations: list[str] = Field(default_factory=list)
    sources: list[SourceRef] = Field(default_factory=list)
    disclaimer: str = DISCLAIMER
    created_by: CreatedBy

    @model_validator(mode="after")
    def _checks(self) -> Self:
        words = len(self.overall_summary.split())
        if words > SUMMARY_MAX_WORDS:
            raise ValueError(f"overall_summary has {words} words (max {SUMMARY_MAX_WORDS})")
        if self.disclaimer != DISCLAIMER:
            raise ValueError("disclaimer must be the fixed DISCLAIMER text")
        ids = [i.issue_id for i in self.issues]
        if len(set(ids)) != len(ids):
            raise ValueError("each issue may appear only once")
        return self
