"""Chunk every judgment and statute section of a snapshot (PLAN 3.7); write chunk stats.

Reads the 3.2 clean texts, 3.3 paragraphs, 3.4 metadata and 3.5 statute sections and writes
``<data_dir>/processed/chunks/<snapshot>.jsonl.gz`` plus ``docs/data/chunk_stats.md``. Every
chunk is checked against its source (the text re-extracted by offsets must be identical) and
against the embedding limit before anything is written. Load into Postgres with
``scripts/load_corpus.py``.

Usage: uv run scripts/chunk_corpus.py [--snapshot ID] [--workers N]
"""

import argparse
import concurrent.futures as cf
import gzip
import itertools
import json
import os
import statistics
import sys
import time
from collections import Counter
from pathlib import Path
from typing import Any

from juris.config import REPO_ROOT, get_settings
from juris.ingest.chunk import LIMIT, chunk_judgment, chunk_statute_section
from juris.ingest.tokens import load_tokenizer

REPORT = REPO_ROOT / "docs" / "data" / "chunk_stats.md"


def _read_gz(path: Path) -> Any:
    with gzip.open(path, "rt", encoding="utf-8") as fh:
        return json.load(fh)


def _judgment(args: tuple[str, str, str, dict[str, Any]]) -> list[dict[str, Any]]:
    data_dir, snapshot, doc_id, meta = args
    base = Path(data_dir) / "interim"
    clean = _read_gz(base / "parsed" / snapshot / f"{doc_id}.json.gz")["clean_text"]
    paras = _read_gz(base / "segmented" / snapshot / f"{doc_id}.json.gz")["paragraphs"]
    chunks = chunk_judgment(doc_id, clean, paras, meta, load_tokenizer())
    for c in chunks:
        if clean[c.char_start : c.char_end] != c.text:
            raise AssertionError(f"{c.chunk_id}: text doesn't match its offsets")
        if c.embed_tokens > LIMIT:
            raise AssertionError(f"{c.chunk_id}: {c.embed_tokens} tokens > {LIMIT}")
    return [c.to_json() for c in chunks]


def pct(values: list[int], q: float) -> int:
    ordered = sorted(values)
    return ordered[min(len(ordered) - 1, int(q * len(ordered)))] if ordered else 0


def write_report(snapshot: str, chunks: list[dict[str, Any]], seconds: float) -> None:
    groups = {
        "All": chunks,
        "Judgments": [c for c in chunks if not c["statute_section_id"]],
        "Statutes": [c for c in chunks if c["statute_section_id"]],
    }
    kinds = Counter(c["kind"] for c in chunks)
    edges = [0, 100, 200, 300, 400, 500, LIMIT + 1]
    tokens = [c["tokens"] for c in chunks]
    hist = Counter(
        next(f"{a}-{b - 1}" for a, b in itertools.pairwise(edges) if t < b) for t in tokens
    )
    lines = [
        "# Chunk statistics (PLAN 3.7)",
        "",
        f"Snapshot `{snapshot}`, generated by `scripts/chunk_corpus.py` ({seconds:.0f} s). "
        "Tokens are counted with the bge-m3 tokenizer (XLM-RoBERTa vocabulary, shared by "
        "multilingual-e5-large). Chunks: `<data_dir>/processed/chunks/<snapshot>.jsonl.gz` and "
        "the `chunks` table.",
        "",
        f"Limit: context header + text + 2 special tokens <= {LIMIT} (multilingual-e5-large's "
        "maximum; bge-m3 takes 8,192). Every chunk was re-extracted from its source by offsets "
        "and compared before writing.",
        "",
        "## Counts and text tokens",
        "",
        "| | Chunks | Documents | Median | p90 | p99 | Max | Max with header |",
        "|---|---|---|---|---|---|---|---|",
    ]
    for name, group in groups.items():
        toks = [c["tokens"] for c in group]
        lines.append(
            f"| {name} | {len(group):,} | {len({c['doc_id'] for c in group}):,} | "
            f"{int(statistics.median(toks)) if toks else 0} | {pct(toks, 0.9)} | "
            f"{pct(toks, 0.99)} | {max(toks, default=0)} | "
            f"{max((c['embed_tokens'] for c in group), default=0)} |"
        )
    lines += [
        "",
        "## Text-token distribution",
        "",
        "| Tokens | Chunks | Share |",
        "|---|---|---|",
        *[
            f"| {k} | {hist[k]:,} | {100 * hist[k] / len(tokens):.1f}% |"
            for k in (f"{a}-{b - 1}" for a, b in itertools.pairwise(edges))
            if hist[k]
        ],
        "",
        "## How chunks were formed",
        "",
        "| Kind | Chunks | Meaning |",
        "|---|---|---|",
        f"| `paragraphs` | {kinds['paragraphs']:,} | one or more whole paragraphs |",
        f"| `sentences` | {kinds['sentences']:,} | a window of a long paragraph, cut between "
        "sentences, ~1 sentence of overlap |",
        f"| `hard` | {kinds['hard']:,} | a window of a paragraph with a sentence longer than "
        "the limit, cut at whitespace |",
        f"| `section` | {kinds['section']:,} | a whole statute section |",
        f"| `section-lines` | {kinds['section-lines']:,} | part of a long statute section, cut "
        "between lines (sub-sections, clauses, illustrations) |",
        "",
        "## Notes",
        "",
        "- Judgment chunk offsets index the 3.2 clean text; `para_start`/`para_end` are "
        "`paragraphs.seq`. Statute chunk offsets index `statute_sections.text`.",
        "- Chunks never cross an opinion part or a front/headnote/body boundary, so some chunks "
        "at those boundaries are small (the 0-99 row).",
        "- Many Supreme Court paragraphs exceed one chunk (long quotations), hence the share of "
        "`sentences` windows; each window's header names the paragraph and the part "
        "(`¶ 12 (part 2/3)`).",
        "- Old reports have inferred paragraphs (3.3), which are layout blocks rather than the "
        "court's paragraphs; their headers say `(unnumbered)`.",
        "",
    ]
    REPORT.parent.mkdir(parents=True, exist_ok=True)
    REPORT.write_text("\n".join(lines), encoding="utf-8")


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Chunk judgments and statutes (PLAN 3.7)")
    parser.add_argument("--snapshot", default="mvp_contract-1f53c208a8")
    parser.add_argument("--workers", type=int, default=max(1, (os.cpu_count() or 2) - 2))
    args = parser.parse_args(argv)

    data_dir = get_settings().data_dir
    started = time.monotonic()
    meta: dict[str, dict[str, Any]] = {}
    with (data_dir / "interim" / "metadata" / args.snapshot / "metadata.jsonl").open(
        encoding="utf-8"
    ) as fh:
        for line in fh:
            record = json.loads(line)
            meta[record["doc_id"]] = record
    seg_dir = data_dir / "interim" / "segmented" / args.snapshot
    judgments = sorted(p.name.removesuffix(".json.gz") for p in seg_dir.glob("*.json.gz"))
    work = [(str(data_dir), args.snapshot, d, meta.get(d, {})) for d in judgments]
    chunks: list[dict[str, Any]] = []
    with cf.ProcessPoolExecutor(max_workers=args.workers) as pool:
        for part in pool.map(_judgment, work, chunksize=8):
            chunks += part
    tok = load_tokenizer()
    for path in sorted((data_dir / "processed" / "statutes").glob("*.jsonl")):
        with path.open(encoding="utf-8") as fh:
            for line in fh:
                section = json.loads(line)
                for c in chunk_statute_section(section, tok):
                    if section["text"][c.char_start : c.char_end] != c.text:
                        raise AssertionError(f"{c.chunk_id}: text doesn't match its offsets")
                    if c.embed_tokens > LIMIT:
                        raise AssertionError(f"{c.chunk_id}: {c.embed_tokens} tokens > {LIMIT}")
                    chunks.append(c.to_json())
    if len({c["chunk_id"] for c in chunks}) != len(chunks):
        raise AssertionError("duplicate chunk IDs")
    out = data_dir / "processed" / "chunks" / f"{args.snapshot}.jsonl.gz"
    out.parent.mkdir(parents=True, exist_ok=True)
    with gzip.open(out.with_suffix(".part"), "wt", encoding="utf-8") as fh:
        for row in chunks:
            fh.write(json.dumps(row, ensure_ascii=False) + "\n")
    out.with_suffix(".part").replace(out)
    write_report(args.snapshot, chunks, time.monotonic() - started)
    print(f"{len(chunks):,} chunks from {len(judgments)} judgments + statutes -> {out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
