"""Export JSON Schemas and TypeScript types for the UI contract (PLAN 2.3).

Writes (serialization mode, i.e. what the backend sends):
    schemas/envelope.schema.json       fields shared by every event
    schemas/event.schema.json          the Event union: every event type and payload
    schemas/case_view.schema.json      the read model (fold of events)
    schemas/case_analysis.schema.json  the final output
    schemas/juris.schema.json          one bundle of all of the above (input for TS)
    schemas/ts/juris.d.ts              TypeScript types (json-schema-to-typescript)

Usage:
    uv run scripts/export_schemas.py            # (re)write everything
    uv run scripts/export_schemas.py --check    # exit 1 if the committed files are stale
    uv run scripts/export_schemas.py --json-only [--check]   # skip TypeScript (no Node)
"""

import json
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path
from typing import Any

from pydantic import TypeAdapter

from juris.config import REPO_ROOT
from juris.events import CaseView, EnvelopeBase, Event
from juris.models import CaseAnalysis

SCHEMAS_DIR = REPO_ROOT / "schemas"
BANNER = "/* Generated by scripts/export_schemas.py from the Pydantic models. Do not edit. */"

TOP_LEVEL: dict[str, tuple[str, Any]] = {
    # file stem: (bundle property / title, type)
    "envelope": ("Envelope", EnvelopeBase),
    "event": ("Event", Event),
    "case_view": ("CaseView", CaseView),
    "case_analysis": ("CaseAnalysis", CaseAnalysis),
}


def _dump(schema: dict[str, Any]) -> str:
    return json.dumps(schema, indent=2, ensure_ascii=False) + "\n"


def _strip_property_titles(node: Any) -> Any:
    """Drop Pydantic's per-field titles so TypeScript gets inline field types, not one alias
    per field. Model and enum titles (in ``$defs``) are kept: those become the named types.
    A ``$ref`` with siblings (``default``, ``description``) is reduced to the bare ``$ref``,
    or json2ts would declare a duplicate alias (``ClaimStatus1``)."""
    if isinstance(node, list):
        return [_strip_property_titles(n) for n in node]
    if not isinstance(node, dict):
        return node
    out = {k: _strip_property_titles(v) for k, v in node.items()}
    if isinstance(out.get("properties"), dict):
        props: dict[str, Any] = {}
        for name, prop in out["properties"].items():
            if isinstance(prop, dict):
                prop = {"$ref": prop["$ref"]} if "$ref" in prop else prop
                prop = {k: v for k, v in prop.items() if k != "title"}
            props[name] = prop
        out["properties"] = props
    return out


def json_schemas() -> dict[str, str]:
    """File name → content for every JSON Schema file."""
    files: dict[str, str] = {}
    for stem, (title, tp) in TOP_LEVEL.items():
        schema = TypeAdapter(tp).json_schema(mode="serialization")
        schema["title"] = title
        files[f"{stem}.schema.json"] = _dump(schema)

    inputs = [(title, "serialization", TypeAdapter(tp)) for title, tp in TOP_LEVEL.values()]
    refs, top = TypeAdapter.json_schemas(inputs, ref_template="#/$defs/{model}")  # type: ignore[arg-type]
    defs: dict[str, Any] = dict(top.get("$defs", {}))
    properties: dict[str, Any] = {}
    for (title, _mode), schema in refs.items():
        if "$ref" not in schema:  # unions (Event) come back inline: give them a named def
            defs[title] = {**schema, "title": title}
            schema = {"$ref": f"#/$defs/{title}"}
        properties[title[0].lower() + title[1:]] = schema
    bundle = {
        "title": "JurisContract",
        "description": "Every type the backend sends to the UI (IDEA_final §12).",
        "type": "object",
        "properties": properties,
        "required": list(properties),
        "additionalProperties": False,
        "$defs": dict(sorted(defs.items())),
    }
    files["juris.schema.json"] = _dump(_strip_property_titles(bundle))
    return files


def typescript(bundle_path: Path, out_path: Path) -> None:
    npx = shutil.which("npx")
    if npx is None:
        raise SystemExit("npx not found: install Node, run `npm ci`, or use --json-only")
    subprocess.run(
        [
            npx,
            "--no-install",
            "json2ts",
            "-i",
            str(bundle_path),
            "-o",
            str(out_path),
            "--unreachableDefinitions",
            "--unknownAny",
            "--bannerComment",
            BANNER,
        ],
        check=True,
        cwd=REPO_ROOT,
    )


def generate(out_dir: Path, with_ts: bool) -> None:
    out_dir.mkdir(parents=True, exist_ok=True)
    for name, content in json_schemas().items():
        (out_dir / name).write_text(content, encoding="utf-8", newline="\n")
    if with_ts:
        (out_dir / "ts").mkdir(exist_ok=True)
        typescript(out_dir / "juris.schema.json", out_dir / "ts" / "juris.d.ts")


def _read(path: Path) -> str:
    return path.read_text(encoding="utf-8").replace("\r\n", "\n") if path.exists() else ""


def stale_files(with_ts: bool) -> list[str]:
    """Files whose committed content differs from a fresh export (line endings ignored)."""
    with tempfile.TemporaryDirectory() as tmp:
        fresh = Path(tmp)
        generate(fresh, with_ts)
        names = [p.relative_to(fresh) for p in fresh.rglob("*") if p.is_file()]
        return [str(n) for n in names if _read(fresh / n) != _read(SCHEMAS_DIR / n)]


def main(argv: list[str]) -> int:
    with_ts = "--json-only" not in argv
    if "--check" in argv:
        stale = stale_files(with_ts)
        if stale:
            print("stale schema files (run: uv run scripts/export_schemas.py):", *stale, sep="\n  ")
            return 1
        print("schemas are up to date")
        return 0
    generate(SCHEMAS_DIR, with_ts)
    print(f"wrote {SCHEMAS_DIR}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
