"""Normalise and merge judgment metadata for a snapshot (PLAN 3.4); write the quality report.

Joins each judgment's AWS metadata row, its KanoonGPT row (``fetch_case_metadata.py``, on CNR)
and the first page of its parsed text, then writes
``<data_dir>/interim/metadata/<snapshot_id>/metadata.jsonl`` and ``docs/data/metadata_quality.md``
(coverage per field and source, cross-source conflicts).

Usage: uv run scripts/normalise_metadata.py [--snapshot ID]
"""

import argparse
import gzip
import json
import sys
from collections import Counter, defaultdict
from pathlib import Path
from typing import Any

import pyarrow.parquet as pq

from juris.config import REPO_ROOT, get_settings
from juris.ingest.metadata import JudgmentMetadata, merge

REPORT = REPO_ROOT / "docs" / "data" / "metadata_quality.md"
FIELDS = [
    "cnr", "title", "petitioner", "respondent", "case_number", "court", "court_level", "judges",
    "author", "bench_strength", "decision_date", "citations", "neutral_citation", "disposition",
    "headnote",
]  # fmt: skip


def load_aws_sc(data_dir: Path, wanted: set[str]) -> dict[str, dict[str, Any]]:
    rows: dict[str, dict[str, Any]] = {}
    for f in sorted((data_dir / "raw" / "aws_sc" / "metadata").glob("*.parquet")):
        for row in pq.read_table(f).to_pylist():
            if row["path"] in wanted:
                rows.setdefault(row["path"], row)  # the same judgment recurs across year files
    return rows


def load_aws_hc(data_dir: Path, wanted: set[str]) -> dict[str, dict[str, Any]]:
    rows: dict[str, dict[str, Any]] = {}
    for f in sorted((data_dir / "raw" / "aws_hc" / "metadata").rglob("*.parquet")):
        for row in pq.read_table(f).to_pylist():
            name = (row.get("pdf_link") or "").rsplit("/", 1)[-1].removesuffix(".pdf")
            if name in wanted:
                rows.setdefault(name, row)
    return rows


def load_kanoongpt(data_dir: Path) -> dict[str, list[dict[str, Any]]]:
    path = data_dir / "raw" / "hf_case_laws" / "structured_v1_subset.parquet"
    by_cnr: dict[str, list[dict[str, Any]]] = defaultdict(list)
    if path.exists():
        for row in pq.read_table(path).to_pylist():
            by_cnr[row["cnr_number"]].append(row)
    return by_cnr


def pick_kanoongpt(rows: list[dict[str, Any]], stem: str) -> dict[str, Any] | None:
    """The KanoonGPT row for this document: the one built from the same source file if any."""
    if not rows:
        return None
    same_file = [r for r in rows if stem in (r.get("source_filename") or "")]
    return (same_file or rows)[0]


def first_page(parsed_dir: Path, doc_id: str) -> str | None:
    path = parsed_dir / f"{doc_id}.json.gz"
    if not path.exists():
        return None
    with gzip.open(path, "rt", encoding="utf-8") as fh:
        text: str = json.load(fh)["clean_text"]
    return text[:8000]


def pct(n: int, total: int) -> str:
    return f"{100 * n / total:.1f}%" if total else "n/a"


def write_report(snapshot_id: str, records: list[JudgmentMetadata], kg_rows: int) -> None:
    groups = {
        "All": records,
        "SC": [r for r in records if r.doc_id.startswith("SC-")],
        "HC": [r for r in records if r.doc_id.startswith("HC-")],
    }
    lines = [
        "# Metadata quality (PLAN 3.4)",
        "",
        f"Snapshot `{snapshot_id}`, generated by `scripts/normalise_metadata.py`. Records: "
        "`<data_dir>/interim/metadata/<snapshot>/metadata.jsonl`. A field no source gives "
        "reliably is left empty (`None`), never guessed.",
        "",
        "Sources: `aws_sc` / `aws_hc` (AWS Open Data metadata, CC-BY-4.0), `kanoongpt` "
        "(KanoonGPT/indian-case-laws structured v1, Apache-2.0, joined on CNR), `text` (the "
        "judgment's own first page: SCR bench line and header citations).",
        "",
        "## Coverage per field",
        "",
        "| Field | " + " | ".join(f"{k} (n={len(v)})" for k, v in groups.items()) + " |",
        "|---|" + "---|" * len(groups),
    ]
    for name in FIELDS:
        cells = []
        for group in groups.values():
            n = sum(1 for r in group if getattr(r, name) not in (None, "", []))
            cells.append(pct(n, len(group)))
        lines.append(f"| `{name}` | " + " | ".join(cells) + " |")

    lines += ["", "## Source of each field", "", "| Field | Sources |", "|---|---|"]
    for name in FIELDS:
        counts = Counter(r.sources[name] for r in records if name in r.sources)
        by_source = ", ".join(f"{s} {n}" for s, n in counts.most_common())
        lines.append(f"| `{name}` | {by_source} |")

    match = Counter(r.kanoongpt_match for r in records)
    conflict_fields = Counter(c.split(":", 1)[0] for r in records for c in r.conflicts)
    examples: dict[str, str] = {}
    for r in records:
        for c in r.conflicts:
            examples.setdefault(c.split(":", 1)[0], f"`{r.doc_id}`: {c}")
    strength = Counter(r.bench_strength for r in records if r.bench_strength)
    dispositions = Counter(r.disposition for r in records if r.disposition)
    lines += [
        "",
        "## KanoonGPT join",
        "",
        f"- Rows fetched for the snapshot: {kg_rows}",
        f"- Judgments joined on CNR (date or title confirmed): {match['cnr']} "
        f"({pct(match['cnr'], len(records))})",
        f"- CNR found but rejected (date and title both disagree): {match['rejected']}",
        f"- Not in KanoonGPT: {match['none']}",
        "",
        "## Conflicts between sources",
        "",
        "Recorded per judgment in `conflicts`; the source that set a field first keeps its value "
        "(AWS, then KanoonGPT, then the text). Bench strength is the strict majority of the "
        "sources that count the bench (coram lists, the AWS card's and KanoonGPT's bench size, "
        "the SCR bench line), and `None` without one.",
        "",
        "| Field | Judgments | Example |",
        "|---|---|---|",
        *[f"| `{k}` | {v} | {examples[k]} |" for k, v in conflict_fields.most_common()],
        "",
        "## Distributions",
        "",
        "- Bench strength: " + ", ".join(f"{k}: {v}" for k, v in sorted(strength.items())),
        "- Disposition: " + ", ".join(f"{k} {v}" for k, v in dispositions.most_common()),
        "",
        "## Known limitations",
        "",
        "- HC disposition: AWS leaves it empty for most Delhi/Bombay judgments and KanoonGPT "
        "adds little; it is not inferred from the judgment text.",
        "- HC citations: Delhi/Bombay judgments before their neutral-citation schemes carry none; "
        "no reporter citations exist in the metadata.",
        "- HC headnotes: none in either source.",
        "- `author` is the AWS card's starred judge, or the sole judge of a one-judge bench; "
        "unmarked multi-judge benches stay `None`.",
        "- Judgments missing from the KanoonGPT revision (the most recent ones) have AWS and text "
        "fields only.",
        "- Old SCR bench lines are OCR-damaged; they only vote on bench strength and fill "
        "`judges` when no metadata source lists the bench.",
        "",
    ]
    REPORT.parent.mkdir(parents=True, exist_ok=True)
    REPORT.write_text("\n".join(lines), encoding="utf-8")


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Normalise judgment metadata (PLAN 3.4)")
    parser.add_argument("--snapshot", default="mvp_contract-1f53c208a8")
    args = parser.parse_args(argv)

    data_dir = get_settings().data_dir
    snapshot = json.loads((data_dir / "snapshots" / f"{args.snapshot}.json").read_text("utf-8"))
    docs = [d for d in snapshot["documents"] if d["kind"] == "judgment"]
    sc = load_aws_sc(data_dir, {d["doc_id"].removeprefix("SC-") for d in docs})
    hc = load_aws_hc(data_dir, {d["doc_id"].removeprefix("HC-") for d in docs})
    kg = load_kanoongpt(data_dir)
    parsed_dir = data_dir / "interim" / "parsed" / args.snapshot
    out_dir = data_dir / "interim" / "metadata" / args.snapshot
    out_dir.mkdir(parents=True, exist_ok=True)

    records = []
    for doc in docs:
        doc_id = doc["doc_id"]
        if doc["source"] == "aws_sc":
            stem = doc_id.removeprefix("SC-")
            aws, source = sc.get(stem), "aws_sc"
        else:
            stem = doc_id.removeprefix("HC-")
            aws, source = hc.get(stem), "aws_hc"
        cnr = (aws or {}).get("cnr")
        kg_row = pick_kanoongpt(kg.get(cnr, []), stem) if cnr else None
        records.append(merge(doc_id, aws, source, kg_row, first_page(parsed_dir, doc_id)))  # type: ignore[arg-type]

    with (out_dir / "metadata.jsonl").open("w", encoding="utf-8") as fh:
        for r in records:
            fh.write(json.dumps(r.to_json(), ensure_ascii=False) + "\n")
    write_report(args.snapshot, records, sum(len(v) for v in kg.values()))
    joined = sum(1 for r in records if r.kanoongpt_match == "cnr")
    print(f"{len(records)} judgments normalised ({joined} joined to KanoonGPT) -> {REPORT}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
