"""Parse and clean every document of a snapshot (PLAN 3.2) and write the parse report.

Writes ``<data_dir>/interim/parsed/<snapshot_id>/<doc_id>.json.gz`` per document (raw text,
clean text, offset runs, page starts, quality signals) and ``docs/data/parse_report.md``.
Resumable: documents already parsed are skipped unless ``--force``.

Usage: uv run scripts/parse_corpus.py [--snapshot ID] [--workers N] [--force]
"""

import argparse
import concurrent.futures as cf
import gzip
import json
import os
import statistics
import sys
import time
from collections import Counter
from pathlib import Path
from typing import Any

from juris.config import REPO_ROOT, get_settings
from juris.ingest.parse import parse_entry

REPORT = REPO_ROOT / "docs" / "data" / "parse_report.md"
SUMMARY_KEYS = (
    "doc_id", "kind", "reason", "source", "text_source", "pages", "raw_chars", "clean_chars",
    "needs_ocr", "latin_ratio", "language", "ocr_noise", "stats", "error",
)  # fmt: skip


def latest_snapshot(data_dir: Path) -> Path:
    snapshots = sorted((data_dir / "snapshots").glob("*.json"), key=lambda p: p.stat().st_mtime)
    if not snapshots:
        raise SystemExit("no snapshot found: run scripts/acquire.py first")
    return snapshots[-1]


def _work(args: tuple[dict[str, Any], str, str]) -> dict[str, Any]:
    entry, data_dir, out_dir = args
    out = Path(out_dir) / f"{entry['doc_id']}.json.gz"
    record = parse_entry(entry, Path(data_dir))
    with gzip.open(out.with_suffix(".part"), "wt", encoding="utf-8") as fh:
        json.dump(record, fh, ensure_ascii=False)
    out.with_suffix(".part").replace(out)
    return {k: record.get(k) for k in SUMMARY_KEYS}


def _summary_of(path: Path) -> dict[str, Any]:
    with gzip.open(path, "rt", encoding="utf-8") as fh:
        record = json.load(fh)
    return {k: record.get(k) for k in SUMMARY_KEYS}


def write_report(snapshot_id: str, rows: list[dict[str, Any]], seconds: float) -> None:
    ok = [r for r in rows if not r.get("error")]
    errors = [r for r in rows if r.get("error")]
    english = [r for r in ok if r["language"] == "en"]
    non_en = [r for r in ok if r["language"] != "en"]
    ocr = [r for r in ok if r["needs_ocr"]]
    judgments = [r for r in ok if r["kind"] == "judgment"]
    dropped: Counter[str] = Counter()
    fixes: Counter[str] = Counter()
    for r in ok:
        for key, n in (r.get("stats") or {}).items():
            (dropped if key.startswith("dropped_") else fixes)[key] += n
    noise = sorted(r["ocr_noise"] for r in judgments)
    noisy = sorted(judgments, key=lambda r: -r["ocr_noise"])[:5]
    by_reason = Counter(r["reason"] for r in rows)
    reasons = ", ".join(f"{k} {v}" for k, v in sorted(by_reason.items()))
    raw = sum(r["raw_chars"] for r in ok)
    clean = sum(r["clean_chars"] for r in ok)

    def pct(a: int, b: int) -> str:
        return f"{100 * a / b:.1f}%" if b else "n/a"

    lines = [
        "# Parse report (PLAN 3.2)",
        "",
        f"Snapshot `{snapshot_id}`, generated by `scripts/parse_corpus.py` ({seconds:.0f} s). "
        "Per-document records: `<data_dir>/interim/parsed/<snapshot>/<doc_id>.json.gz`.",
        "",
        "## Summary",
        "",
        "| | Count |",
        "|---|---|",
        f"| Documents | {len(rows)} ({reasons}) |",
        f"| Parsed without error | **{len(ok)} ({pct(len(ok), len(rows))})** |",
        f"| Errors | {len(errors)} |",
        f"| Need OCR (< 200 chars/page) | {len(ocr)} |",
        f"| English (kept) | {len(english)} |",
        f"| Non-English (dropped for the MVP) | {len(non_en)} |",
        f"| Pages | {sum(r['pages'] for r in ok):,} |",
        f"| Characters raw -> clean | {raw:,} -> {clean:,} ({pct(raw - clean, raw)} removed) |",
        "",
        "Text source: judgments use the PDF text layer (pdfium). Pre-~1990 SC volumes carry the "
        "source's own OCR layer; no OCR engine runs here (D-020). Statutes use the provided text.",
        "",
        "## Lines dropped, by rule",
        "",
        "| Rule | Lines |",
        "|---|---|",
        *[f"| `{k.removeprefix('dropped_')}` | {v:,} |" for k, v in dropped.most_common()],
        "",
        "## Characters fixed",
        "",
        "| Fix | Count |",
        "|---|---|",
        *[f"| `{k}` | {v:,} |" for k, v in fixes.most_common() if k != "lines_kept"],
        "",
        "## OCR quality (judgments)",
        "",
        "`ocr_noise` = share of tokens with symbols inside words (e.g. `SUPl{EMl!`).",
        "",
        f"- median {statistics.median(noise):.4f}, 90th percentile "
        f"{noise[int(0.9 * (len(noise) - 1))]:.4f}, max {noise[-1]:.4f}"
        if noise
        else "- no judgments",
        f"- documents with noise > 1%: {sum(1 for n in noise if n > 0.01)}",
        "",
        "Noisiest:",
        "",
        *[f"- `{r['doc_id']}`: {r['ocr_noise']:.4f}" for r in noisy],
        "",
        "## Known limitations",
        "",
        "- Old SC volumes keep their OCR errors and marginal notes (dates, case names) inline; "
        "see `ocr_noise` above. Heavily damaged running heads can survive (rare).",
        "- About 40 digital-signature lines survive where the text layer merges a footnote "
        "citation and the stamp into one line (`2 Digitally Signed (2012) 1 SCC 656`); removing "
        "them would risk the citation.",
        "- A line-initial `A` after a sentence end is kept (it may be the article); B-H margin "
        "letters are always stripped in documents that use them.",
        "- Case-name running heads on alternate pages are dropped only when they recur on at "
        "least 30% of pages.",
        "- Line structure is kept (one output line per source line); paragraphs are assembled "
        "in PLAN 3.3.",
        "",
        "## Errors",
        "",
        *([f"- `{r['doc_id']}`: {r['error']}" for r in errors] or ["None."]),
        "",
        "## Non-English documents",
        "",
        *([f"- `{r['doc_id']}` (latin ratio {r['latin_ratio']})" for r in non_en] or ["None."]),
        "",
    ]
    REPORT.parent.mkdir(parents=True, exist_ok=True)
    REPORT.write_text("\n".join(lines), encoding="utf-8")


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Parse and clean a snapshot (PLAN 3.2)")
    parser.add_argument("--snapshot", help="snapshot ID (default: the latest)")
    parser.add_argument("--workers", type=int, default=max(1, (os.cpu_count() or 2) - 2))
    parser.add_argument("--force", action="store_true", help="re-parse documents already done")
    args = parser.parse_args(argv)

    data_dir = get_settings().data_dir
    path = (
        (data_dir / "snapshots" / f"{args.snapshot}.json")
        if args.snapshot
        else latest_snapshot(data_dir)
    )
    snapshot = json.loads(path.read_text(encoding="utf-8"))
    out_dir = data_dir / "interim" / "parsed" / snapshot["snapshot_id"]
    out_dir.mkdir(parents=True, exist_ok=True)

    started = time.monotonic()
    todo, rows = [], []
    for entry in snapshot["documents"]:
        done = out_dir / f"{entry['doc_id']}.json.gz"
        if done.exists() and not args.force:
            rows.append(_summary_of(done))
        else:
            todo.append((entry, str(data_dir), str(out_dir)))
    print(
        f"{snapshot['snapshot_id']}: {len(rows)} already parsed, {len(todo)} to parse", flush=True
    )
    with cf.ProcessPoolExecutor(max_workers=args.workers) as pool:
        for n, row in enumerate(pool.map(_work, todo, chunksize=4), start=1):
            rows.append(row)
            if n % 250 == 0:
                print(f"  {n}/{len(todo)}", flush=True)
    rows.sort(key=lambda r: r["doc_id"])
    (out_dir / "_summary.json").write_text(json.dumps(rows, indent=1) + "\n", encoding="utf-8")
    write_report(snapshot["snapshot_id"], rows, time.monotonic() - started)
    ok = sum(1 for r in rows if not r.get("error"))
    print(f"parsed OK {ok}/{len(rows)}; report -> {REPORT}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
