"""Segment every parsed judgment into paragraphs (PLAN 3.3) and write the segmentation report.

Reads ``<data_dir>/interim/parsed/<snapshot_id>/<doc_id>.json.gz`` (from parse_corpus.py) and
writes ``<data_dir>/interim/segmented/<snapshot_id>/<doc_id>.json.gz`` per English judgment
(paragraphs with clean-text offsets, pages, numbering, part, sub-markers, contested flag) and
``docs/data/segmentation_report.md``. Statutes are sectioned later (PLAN 3.6), not here.

Usage: uv run scripts/segment_corpus.py [--snapshot ID] [--workers N]
"""

import argparse
import concurrent.futures as cf
import dataclasses
import gzip
import json
import os
import sys
import time
from collections import Counter, defaultdict
from pathlib import Path
from typing import Any

from juris.config import REPO_ROOT, get_settings
from juris.ingest.segment import segment

REPORT = REPO_ROOT / "docs" / "data" / "segmentation_report.md"


def latest_parsed(data_dir: Path) -> Path:
    runs = sorted((data_dir / "interim" / "parsed").glob("*/_summary.json"), key=os.path.getmtime)
    if not runs:
        raise SystemExit("no parsed snapshot found: run scripts/parse_corpus.py first")
    return runs[-1].parent


def era(doc_id: str) -> str:
    if doc_id.startswith("HC-"):
        return "HC"
    year = int(doc_id.removeprefix("SC-").removeprefix("S_")[:4])
    return f"SC {year // 10 * 10}s"


def _work(args: tuple[str, str]) -> dict[str, Any] | None:
    src, out_dir = args
    with gzip.open(src, "rt", encoding="utf-8") as fh:
        record = json.load(fh)
    if record.get("kind") != "judgment" or record.get("language") != "en" or record.get("error"):
        return None
    seg = segment(record["clean_text"], record["page_starts"])
    doc = {
        "doc_id": record["doc_id"],
        "numbering": seg.numbering,
        "parts": seg.parts,
        "missing_numbers": seg.missing_numbers,
        "paragraphs": [dataclasses.asdict(p) for p in seg.paragraphs],
    }
    out = Path(out_dir) / f"{record['doc_id']}.json.gz"
    with gzip.open(out.with_suffix(".part"), "wt", encoding="utf-8") as fh:
        json.dump(doc, fh, ensure_ascii=False)
    out.with_suffix(".part").replace(out)
    explicit = [p for p in seg.paragraphs if p.numbering == "explicit"]
    return {
        "doc_id": record["doc_id"],
        "era": era(record["doc_id"]),
        "numbering": seg.numbering,
        "parts": seg.parts,
        "paragraphs": len(seg.paragraphs),
        "explicit": len(explicit),
        "body": sum(1 for p in seg.paragraphs if p.section == "body"),
        "headnote": sum(1 for p in seg.paragraphs if p.section == "headnote"),
        "missing": len(seg.missing_numbers),
        "contested": sum(1 for p in explicit if p.contested),
        "starts_at_1": bool(explicit) and explicit[0].no.split("-")[0] == "1",
    }


def write_report(snapshot_id: str, rows: list[dict[str, Any]], seconds: float) -> None:
    by_era: dict[str, list[dict[str, Any]]] = defaultdict(list)
    for r in rows:
        by_era[r["era"]].append(r)
    explicit = [r for r in rows if r["numbering"] == "explicit"]
    n_explicit = sum(r["explicit"] for r in explicit)
    parts = Counter(r["parts"] for r in explicit)

    def pct(a: int, b: int) -> str:
        return f"{100 * a / b:.1f}%" if b else "n/a"

    era_rows = []
    for key in sorted(by_era, key=lambda k: (k != "HC", k)):
        group = by_era[key]
        ex = [r for r in group if r["numbering"] == "explicit"]
        paras = sum(r["explicit"] for r in ex)
        era_rows.append(
            f"| {key} | {len(group)} | {len(ex)} ({pct(len(ex), len(group))}) | {paras:,} | "
            f"{sum(r['missing'] for r in ex)} | {pct(sum(r['contested'] for r in ex), paras)} |"
        )
    lines = [
        "# Segmentation report (PLAN 3.3)",
        "",
        f"Snapshot `{snapshot_id}`, generated by `scripts/segment_corpus.py` ({seconds:.0f} s). "
        "Per-document paragraphs: `<data_dir>/interim/segmented/<snapshot>/<doc_id>.json.gz`. "
        "Method and the hand-checked sample: [segmentation_check.md](segmentation_check.md).",
        "",
        "## Summary",
        "",
        "| | Count |",
        "|---|---|",
        f"| English judgments | {len(rows)} |",
        f"| With the judgment's own numbering (explicit) | {len(explicit)} "
        f"({pct(len(explicit), len(rows))}) |",
        f"| Inferred (`p-N`, no numbering in the source) | {len(rows) - len(explicit)} |",
        f"| Numbered paragraphs | {n_explicit:,} |",
        f"| Explicit judgments whose numbering starts at 1 | "
        f"{sum(r['starts_at_1'] for r in explicit)} |",
        f"| Numbers missing inside a chain (lost to OCR/layout) | "
        f"{sum(r['missing'] for r in explicit):,} |",
        f"| Paragraphs flagged `contested` | {sum(r['contested'] for r in explicit):,} "
        f"({pct(sum(r['contested'] for r in explicit), n_explicit)}) |",
        f"| Headnote paragraphs labelled | {sum(r['headnote'] for r in rows):,} |",
        "",
        "Opinions (parts) per explicit judgment: "
        + ", ".join(f"{k}: {v}" for k, v in sorted(parts.items())),
        "",
        "## By court and era",
        "",
        "| Group | Judgments | Explicit | Numbered paragraphs | Missing numbers | Contested |",
        "|---|---|---|---|---|---|",
        *era_rows,
        "",
    ]
    REPORT.parent.mkdir(parents=True, exist_ok=True)
    REPORT.write_text("\n".join(lines), encoding="utf-8")


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Segment parsed judgments (PLAN 3.3)")
    parser.add_argument("--snapshot", help="snapshot ID (default: the latest parsed)")
    parser.add_argument("--workers", type=int, default=max(1, (os.cpu_count() or 2) - 2))
    args = parser.parse_args(argv)

    data_dir = get_settings().data_dir
    src_dir = (
        data_dir / "interim" / "parsed" / args.snapshot
        if args.snapshot
        else latest_parsed(data_dir)
    )
    out_dir = data_dir / "interim" / "segmented" / src_dir.name
    out_dir.mkdir(parents=True, exist_ok=True)
    started = time.monotonic()
    todo = [(str(p), str(out_dir)) for p in sorted(src_dir.glob("*.json.gz"))]
    with cf.ProcessPoolExecutor(max_workers=args.workers) as pool:
        rows = [r for r in pool.map(_work, todo, chunksize=8) if r]
    rows.sort(key=lambda r: r["doc_id"])
    (out_dir / "_summary.json").write_text(json.dumps(rows, indent=1) + "\n", encoding="utf-8")
    write_report(src_dir.name, rows, time.monotonic() - started)
    explicit = sum(1 for r in rows if r["numbering"] == "explicit")
    print(f"{src_dir.name}: segmented {len(rows)} judgments ({explicit} explicit) -> {REPORT}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
