"""The hand-labelled claim-passage pairs for the Citation Verifier's entailment check (PLAN 6.1).

Usage:
    uv run scripts/verifier_pairs.py candidates   # working file of dev-item pinpoint passages
    uv run scripts/verifier_pairs.py check        # validate eval/verifier/juris_pairs.yaml

``candidates`` writes, for every gold authority pinpoint of a dev item, the paragraph and the
chunk that contains it, to ``<data_dir>/wip/verifier_6_1/candidates.jsonl`` (not committed).
``check`` validates the committed set against the corpus database.
"""

import argparse
import json
import sys
from collections import Counter
from pathlib import Path
from typing import Any

import yaml
from sqlalchemy import create_engine, text
from sqlalchemy.engine import Connection

from juris.config import get_settings
from juris.verify.quote import quote_in_text

ROOT = Path(__file__).resolve().parent.parent
DEV = ROOT / "eval" / "juris_eval" / "dev.jsonl"
PAIRS = ROOT / "eval" / "verifier" / "juris_pairs.yaml"


def wip_dir() -> Path:
    """Working files (candidates, the spec), outside the repo under the data directory."""
    return get_settings().data_dir / "wip" / "verifier_6_1"


LABELS = ("supports", "partially_supports", "does_not_support", "contradicts")
CONSTRUCTIONS = (
    "gold",
    "paraphrase",
    "overstated",
    "dropped_condition",
    "negated",
    "wrong_passage",
    "argument_only",
    "other",
)
EXPECTED = 50
MAX_PER_CHUNK = 4
MIN_CHUNKS = 20
HEADER = """# Juris verifier pairs (PLAN 6.1): hand-labelled pairs for the entailment check.
# Generated by `uv run scripts/verifier_pairs.py build`; see eval/verifier/README.md.
# Validate with `uv run scripts/verifier_pairs.py check`.
"""
FIELDS = (
    "id",
    "item",
    "doc_id",
    "chunk_id",
    "pinpoint",
    "claim",
    "quote",
    "passage",
    "label",
    "construction",
    "rationale",
)


def containing_chunk(conn: Connection, doc_id: str, no: str) -> dict[str, Any] | None:
    """The paragraph ``no`` of the document and the chunk whose character span covers it."""
    para = conn.execute(
        text(
            "SELECT seq, text, char_start, char_end FROM paragraphs "
            "WHERE doc_id = :d AND no = :n ORDER BY seq LIMIT 1"
        ),
        {"d": doc_id, "n": no},
    ).one_or_none()
    if para is None:
        return None
    chunk = conn.execute(
        text(
            "SELECT chunk_id, text, para_start, para_end FROM chunks "
            "WHERE doc_id = :d AND char_start <= :s AND char_end >= :e "
            "ORDER BY (char_end - char_start) LIMIT 1"
        ),
        {"d": doc_id, "s": para[2], "e": para[3]},
    ).one_or_none()
    if chunk is None:  # a paragraph split across chunks: the one holding its start
        chunk = conn.execute(
            text(
                "SELECT chunk_id, text, para_start, para_end FROM chunks "
                "WHERE doc_id = :d AND char_start <= :s AND char_end > :s LIMIT 1"
            ),
            {"d": doc_id, "s": para[2]},
        ).one_or_none()
    return {
        "paragraph": para[1],
        "chunk_id": chunk[0] if chunk else None,
        "chunk_text": chunk[1] if chunk else None,
    }


def candidates() -> int:
    wip = wip_dir()
    wip.mkdir(parents=True, exist_ok=True)
    engine = create_engine(get_settings().database_url())
    rows = 0
    unmapped: list[str] = []
    with engine.connect() as conn, (wip / "candidates.jsonl").open("w", encoding="utf-8") as out:
        for line in DEV.read_text(encoding="utf-8").splitlines():
            item = json.loads(line)
            for kind in ("supporting", "contrary"):
                for a in item[f"gold_{kind}_authorities"]:
                    for pin in a["pinpoints"]:
                        got = containing_chunk(conn, a["doc_id"], pin)
                        if got is None or got["chunk_id"] is None:
                            unmapped.append(f"{item['id']} {a['doc_id']} {pin}")
                            continue
                        rec = {
                            "item": item["id"],
                            "kind": kind,
                            "doc_id": a["doc_id"],
                            "title": a["title"],
                            "pinpoint": pin,
                            "proposition": a["proposition"],
                            "paragraph": got["paragraph"],
                            "chunk_id": got["chunk_id"],
                            "chunk_text": got["chunk_text"],
                        }
                        out.write(json.dumps(rec, ensure_ascii=False) + "\n")
                        rows += 1
    print(f"{rows} candidates -> {wip / 'candidates.jsonl'}")
    for u in unmapped:
        print(f"  UNMAPPED {u}")
    return 0


def validate(conn: Connection, pairs: list[dict[str, Any]]) -> list[str]:
    problems: list[str] = []
    if len(pairs) != EXPECTED:
        problems.append(f"{len(pairs)} pairs, expected {EXPECTED}")
    ids = [p.get("id") for p in pairs]
    problems += [f"duplicate id {i}" for i, n in Counter(ids).items() if n > 1]
    per_chunk = Counter(p.get("chunk_id") for p in pairs)
    problems += [
        f"chunk {c} used {n} times (max {MAX_PER_CHUNK})"
        for c, n in per_chunk.items()
        if n > MAX_PER_CHUNK
    ]
    if len(per_chunk) < MIN_CHUNKS:
        problems.append(f"{len(per_chunk)} distinct chunks, need {MIN_CHUNKS}")
    cache: dict[str, str | None] = {}
    for p in pairs:
        pid = p.get("id", "?")
        missing = [f for f in FIELDS if not str(p.get(f) or "").strip()]
        if missing:
            problems.append(f"{pid}: missing {', '.join(missing)}")
            continue
        if p["label"] not in LABELS:
            problems.append(f"{pid}: label {p['label']!r}")
        if p["construction"] not in CONSTRUCTIONS:
            problems.append(f"{pid}: construction {p['construction']!r}")
        if not quote_in_text(p["quote"], p["passage"]):
            problems.append(f"{pid}: quote is not in the passage")
        cid = p["chunk_id"]
        if cid not in cache:
            cache[cid] = conn.execute(
                text("SELECT text FROM chunks WHERE chunk_id = :c"), {"c": cid}
            ).scalar()
        if cache[cid] is None:
            problems.append(f"{pid}: chunk {cid} is not in the corpus")
        elif cache[cid] != p["passage"]:
            problems.append(f"{pid}: passage differs from the corpus text of {cid}")
        if not cid.startswith(f"{p['doc_id']}#"):
            problems.append(f"{pid}: chunk {cid} is not of document {p['doc_id']}")
        else:
            got = containing_chunk(conn, p["doc_id"], str(p["pinpoint"]))
            if got is None or got["chunk_id"] != cid:
                problems.append(f"{pid}: pinpoint {p['pinpoint']} is not in chunk {cid}")
        if "reviewed_by" not in p:
            problems.append(f"{pid}: missing reviewed_by")
    return problems


def check() -> int:
    pairs = yaml.safe_load(PAIRS.read_text(encoding="utf-8"))["pairs"]
    engine = create_engine(get_settings().database_url())
    with engine.connect() as conn:
        problems = validate(conn, pairs)
    print(
        f"{len(pairs)} pairs, {len({p['chunk_id'] for p in pairs})} distinct chunks, "
        f"{len({p['item'] for p in pairs})} items"
    )
    labels = Counter(p["label"] for p in pairs)
    print("labels:", ", ".join(f"{k}={labels.get(k, 0)}" for k in LABELS))
    cons = Counter(p["construction"] for p in pairs)
    print("constructions:", ", ".join(f"{k}={v}" for k, v in sorted(cons.items())))
    for p in problems:
        print(f"  PROBLEM {p}")
    print("OK" if not problems else f"{len(problems)} problems")
    return 1 if problems else 0


def _literal(dumper: yaml.SafeDumper, data: str) -> yaml.ScalarNode:
    """Multi-line strings as block scalars where YAML allows it, so passages stay readable."""
    style = "|" if "\n" in data else None
    return dumper.represent_scalar("tag:yaml.org,2002:str", data, style=style)


def build(spec_path: Path) -> int:
    """Write the committed pairs file from a spec (labels, claims, quotes) of the hand work.

    The spec carries everything a person decides; ``doc_id`` and ``passage`` are filled from
    the corpus so the passage is the chunk's exact text. Ids are assigned in spec order.
    """
    spec = yaml.safe_load(spec_path.read_text(encoding="utf-8"))
    engine = create_engine(get_settings().database_url())
    pairs: list[dict[str, Any]] = []
    with engine.connect() as conn:
        for i, s in enumerate(spec, 1):
            doc_id, _, _ = s["chunk_id"].partition("#")
            passage = conn.execute(
                text("SELECT text FROM chunks WHERE chunk_id = :c"), {"c": s["chunk_id"]}
            ).scalar()
            if passage is None:
                print(f"  PROBLEM {s['chunk_id']}: not in the corpus")
                return 1
            pairs.append(
                {
                    "id": f"VP-{i:03d}",
                    "item": s["item"],
                    "doc_id": doc_id,
                    "chunk_id": s["chunk_id"],
                    "pinpoint": s["pinpoint"],
                    "claim": s["claim"],
                    "quote": s["quote"],
                    "passage": passage,
                    "label": s["label"],
                    "construction": s["construction"],
                    "rationale": s["rationale"],
                    "reviewed_by": None,
                }
            )
    yaml.add_representer(str, _literal, Dumper=yaml.SafeDumper)
    body = yaml.dump(
        {"pairs": pairs}, Dumper=yaml.SafeDumper, allow_unicode=True, sort_keys=False, width=100
    )
    PAIRS.parent.mkdir(parents=True, exist_ok=True)
    PAIRS.write_text(HEADER + body, encoding="utf-8", newline="\n")
    print(f"wrote {len(pairs)} pairs -> {PAIRS}")
    return 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Verifier claim-passage pairs (PLAN 6.1)")
    parser.add_argument("command", choices=["candidates", "build", "check"])
    parser.add_argument("--spec", type=Path, help="build: the spec (default: the wip folder)")
    args = parser.parse_args(argv)
    if args.command == "candidates":
        return candidates()
    if args.command == "build":
        return build(args.spec or wip_dir() / "spec.yaml")
    return check()


if __name__ == "__main__":
    sys.exit(main())
